### ISSUE TITLE
Share Map throws error when a null-facing vendor unit is a part of the shared units.

### ISSUE THREAD

**Issue by erindaylli** [Billups/Product#21]
steps to repro:

1. create campaign (min data required)
2. import units 
https://drive.google.com/open?id=1jK99SZulk5Tjbs635LKeJAtd7GlyXtzU
3. import POIs 
https://drive.google.com/open?id=1fg9cphgJ_CbTo_osCFaHQAZg0qL_D3Vu
4. Share campaign
5. click on Proposed check and notice the browser goes blank

**Comment by erindaylli** [comment]
https://billups.edge.boohma.com/map/share/3f8c6cd8-c370-48bc-97e2-ad226f6b0edd#3.89/39.5/-98.35

**Comment by losinggeneration** [comment]
> https://billups.edge.boohma.com/map/share/3f8c6cd8-c370-48bc-97e2-ad226f6b0edd#3.89/39.5/-98.35

```
TypeError: e.Facing is null[Learn More]
```

**Comment by marcgarygray** [comment]
This is resolved by https://github.com/Billups/zisa/pull/699.
We are not currently displaying the correct icon for units with no facing information, but this error has been corrected and there is a separate issue for correcting the icon here:
https://github.com/Billups/zisa/issues/700
