### ISSUE TITLE
Unit description is not getting truncated in unit drawer

### ISSUE THREAD

**Issue by erindaylli** [Billups/Product#29]
https://billups.atlassian.net/secure/RapidBoard.jspa?rapidView=31&modal=detail&selectedIssue=PRODUCT-439

**Comment by aviato** [comment]
Looks like this might have been fixed already @erindaylli 
<img width="385" alt="screen shot 2018-12-19 at 4 27 44 pm" src="https://user-images.githubusercontent.com/7855907/50256884-5f9f1f00-03ad-11e9-85c1-191d1d03801b.png">

**Comment by marcgarygray** [comment]
This PR should have hopefully resolved it:

https://github.com/Billups/zisa/pull/721 <https://github.com/Billups/zisa/pull/721>

 <http://www.billups.com/>

**Comment by aviato** [comment]
Ah ok - thanks @marcgarygray

**Comment by erindaylli** [comment]
It is fixed indeed - nice! Closing
