### ISSUE TITLE
Availability Status Selection - ux

### ISSUE THREAD

**Issue by erindaylli** [Billups/Product#35]

**Comment by erindaylli** [comment]
Need validation from Usability:

Would like the Availability Status menu to close right after I make a selection or close on second click. Currently I need to click outside of the menu and it's clunky because I frequently end up expanding the drawer.

**Comment by erindaylli** [comment]
@losinggeneration how can I tag Zac on issues?

**Comment by zacbates** [comment]
Let's just make it a hover interaction:

![availability-hover-1](https://user-images.githubusercontent.com/43830661/50035366-97295800-ffb6-11e8-9fd3-0e22e0e91b3c.gif)

**Comment by erindaylli** [comment]
@marcgarygray we need to revisit this, I'm afraid. The hover state does not allow me to interact with the drop down

**Comment by marcgarygray** [comment]
@erindaylli I'm seeing that as well. Reopening and revisiting.

**Comment by erindaylli** [comment]
Changing priority to P1 as right now user is unable to change status
