### ISSUE TITLE
'Search' hover state is not correct

### ISSUE THREAD

**Issue by erindaylli** [Billups/Product#47]

**Comment by erindaylli** [comment]
![screen shot 2018-12-20 at 3 11 12 pm](https://user-images.githubusercontent.com/43833184/50315943-8b7fda80-0469-11e9-8cc8-d50f9055c9f5.png)

**Comment by marcgarygray** [comment]
I am not able to reproduce this bug. Perhaps this was fixed as a side effect of a different change since this issue was created? Please verify if you don't mind. :)

**Comment by erindaylli** [comment]
don't mind at all! closing as it's working now
