### ISSUE TITLE
post summit: allow user to change format type for single unit (not just the group)

### ISSUE THREAD

**Issue by erindaylli** [Billups/Product#8]

**Comment by erindaylli** [comment]
* remove Camel Casing when entering a format name
* do not prompt user to confirm the change

I can add a separate ticket for this

**Comment by marcgarygray** [comment]
I found another bug where if the user deletes the media type (effectively changing the media type to ""), and tabs out of the field, a request is sent to `harebrane` to change the media type name to "" which it rejects. To prevent this, if the user leaves the field blank and tabs out, it resets to its initial state.
